[package]
name = "esp-hal-smartled"
version = "0.18.0"
edition = "2024"
rust-version = "1.95"
description = "RMT peripheral adapter for smart LEDs"
repository = "https://github.com/esp-rs/esp-hal-community"
license = "MIT OR Apache-2.0"

[package.metadata.docs.rs]
# use a RISC-V chip and target for docs.rs as it doesn’t require a special compiler
# also enable all optional features
features = ["esp32c6", "esp-hal/unstable", "defmt"]
default-target = "riscv32imac-unknown-none-elf"
targets = ["riscv32imac-unknown-none-elf"]

[dependencies]
defmt = { version = "1", optional = true }
document-features = "0.2.12"
esp-hal = { version = "~1.2", default-features = false, features = ["requires-unstable"] }
num-traits = { version = "0.2", default-features = false }
smart-leds-trait = "0.3"
thiserror = { version = "2.0", default-features = false }

[dev-dependencies]
defmt = "1"
embassy-executor = "0.10"
embassy-futures = "0.1.2"
embassy-time = "0.5"
embedded-graphics = { version = "0.8" }
esp-backtrace = { version = "0.20", features = ["panic-handler", "println"] }
esp-bootloader-esp-idf = { version = "0.6.0" }
esp-hal = { version = "~1.2", features = ["unstable"] }
esp-println = { version = "0.18", features = ["auto", "defmt-espflash"] }
esp-rtos = { version = "0.4", features = ["embassy"] }
smart-leds = "0.4"

[features]
## Implement `defmt::Format` on certain types.
defmt = [
  "dep:defmt",
  "esp-bootloader-esp-idf/defmt",
  "esp-hal/defmt",
  "esp-rtos/defmt",
]

# Chip flags are meant for testing only, so they are not marked for documentation.

esp32 = [
  "esp-backtrace/esp32",
  "esp-bootloader-esp-idf/esp32",
  "esp-hal/esp32",
  "esp-println/esp32",
  "esp-rtos/esp32",
]
# C2: no RMT
esp32c3 = [
  "esp-backtrace/esp32c3",
  "esp-bootloader-esp-idf/esp32c3",
  "esp-hal/esp32c3",
  "esp-println/esp32c3",
  "esp-rtos/esp32c3",
]
esp32c5 = [
  "esp-backtrace/esp32c5",
  "esp-bootloader-esp-idf/esp32c5",
  "esp-hal/esp32c5",
  "esp-println/esp32c5",
  "esp-rtos/esp32c5",
]
esp32c6 = [
  "esp-backtrace/esp32c6",
  "esp-bootloader-esp-idf/esp32c6",
  "esp-hal/esp32c6",
  "esp-println/esp32c6",
  "esp-rtos/esp32c6",
]
# C61: no RMT
esp32h2 = [
  "esp-backtrace/esp32h2",
  "esp-bootloader-esp-idf/esp32h2",
  "esp-hal/esp32h2",
  "esp-println/esp32h2",
  "esp-rtos/esp32h2",
]
esp32p4 = [
  "esp-backtrace/esp32p4",
  "esp-bootloader-esp-idf/esp32p4",
  "esp-hal/esp32p4",
  "esp-println/esp32p4",
  "esp-rtos/esp32p4",
]
esp32s2 = [
  "esp-backtrace/esp32s2",
  "esp-bootloader-esp-idf/esp32s2",
  "esp-hal/esp32s2",
  "esp-println/esp32s2",
  "esp-rtos/esp32s2",
]
esp32s3 = [
  "esp-backtrace/esp32s3",
  "esp-bootloader-esp-idf/esp32s3",
  "esp-hal/esp32s3",
  "esp-println/esp32s3",
  "esp-rtos/esp32s3",
]
esp32s31 = [
  "esp-backtrace/esp32s31",
  "esp-bootloader-esp-idf/esp32s31",
  "esp-hal/esp32s31",
  "esp-println/esp32s31",
  "esp-rtos/esp32s31",
]
