[build]
target = "riscv32imac-unknown-none-elf"
# target = "riscv32imc-unknown-none-elf"
# target = "xtensa-esp32s2-none-elf"
# target = "xtensa-esp32s3-none-elf"
# target = "xtensa-esp32-none-elf"

[target.'cfg(target_arch = "riscv32")']
runner    = "espflash flash --monitor"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
]

[target.'cfg(target_arch = "xtensa")']
runner    = "espflash flash --monitor"
rustflags = [
  # GNU LD
  "-C", "link-arg=-Wl,-Tlinkall.x",
  "-C", "link-arg=-nostartfiles",

  # LLD
  # "-C", "link-arg=-Tlinkall.x",
  # "-C", "linker=rust-lld",
]

[unstable]
build-std = ["alloc", "core"]
